const modulo1 = require('./moduloJ')
const modulo2 = require('./moduloK')

console.log(modulo1.numero)
console.log(modulo1.par)
console.log(modulo1.primo)
console.log('\n', modulo1)
console.log(modulo2.bomDia)
console.log(modulo2.boaTarde())
console.log('\n', modulo2)